name: ncurses-launch
version: current
summary: Fixes for ncurses applications
description: |
  This part provides fixes for ncurses applications to function correctly.

grade: stable
confinement: strict

parts:
  ncurses-launch:
    source: launchers
    plugin: dump
    organize:
      '*-launch': bin/
    stage-packages:
    - ncurses-base
